In [1]:
import pandas as pd

In [2]:
df_transactions = pd.read_csv('../data/raw/transactions.csv',encoding='utf-8')
df_customers = pd.read_csv('../data/raw/customers.csv',encoding='utf-8')

In [3]:
df = pd.merge(
    df_transactions,
    df_customers,
    left_on='sender_id',
    right_on='customer_id',
    how='inner'
)

In [15]:
df.head()

,transaction_id,timestamp,sender_id,receiver_id,amount,device_type,fraud,customer_id,cpf,age,gender,pix_key,account_type,city
0,1,2025-07-09 23:11:19,51,525,705.05,mobile,0,51,069.753.842-74,61,F,sajoao-lucas@example.net,corrente,Ferreira de Santos
1,2,2025-04-15 05:19:52,783,581,480.89,mobile,0,783,423.596.701-07,29,M,sramos@example.org,corrente,Lima da Prata
2,3,2025-05-09 03:03:49,324,937,2198.60,app,0,324,164.850.329-24,23,M,lucas89@example.net,corrente,Ramos
3,4,2025-07-18 12:06:22,789,845,2219.27,mobile,0,789,453.876.190-75,24,F,brendaalmeida@example.net,corrente,Sales da Mata
4,5,2025-05-08 00:42:09,141,769,4627.92,app,0,141,910.342.857-50,28,M,scamara@example.net,poupança,Pinto

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  15000 non-null  int64
 1   timestamp       15000 non-null  object
 2   sender_id       15000 non-null  int64
 3   receiver_id     15000 non-null  int64
 4   amount          15000 non-null  float64
 5   device_type     15000 non-null  object
 6   fraud           15000 non-null  int64
 7   customer_id     15000 non-null  int64
 8   cpf             15000 non-null  object
 9   age             15000 non-null  int64
 10  gender          15000 non-null  object
 11  pix_key         15000 non-null  object
 12  account_type    15000 non-null  object
 13  city            15000 non-null  object
dtypes: float64(1), int64(6), object(7)
memory usage: 1.6+ MB

In [7]:
df.nunique()

transaction_id    15000
timestamp         14997
sender_id          1000
receiver_id        1000
amount            14724
device_type           3
fraud                 2
customer_id        1000
cpf                1000
age                  62
gender                2
pix_key             998
account_type          2
city                555
dtype: int64

In [12]:
df[['fraud','age','amount']].describe()

              fraud           age        amount
count  15000.000000  15000.000000  15000.000000
mean       0.074333     49.457800   2016.962651
std        0.262321     18.152761   2015.120390
min        0.000000     18.000000      1.000000
25%        0.000000     34.000000    591.380000
50%        0.000000     50.000000   1404.860000
75%        0.000000     66.000000   2767.150000
max        1.000000     79.000000  18440.320000

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.isnull().sum()

transaction_id    0
timestamp         0
sender_id         0
receiver_id       0
amount            0
device_type       0
fraud             0
customer_id       0
cpf               0
age               0
gender            0
pix_key           0
account_type      0
city              0
dtype: int64